version: "3"
services:
  nginx:
    ports:
      - "80:80" # specify port mapping 
  node-app:
    deploy:
      replicas: 8
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 15s
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_USER=stephen
      - MONGO_PASSWORD=steve1234
      - SESSION_SECRET=secret
    command: node app.js
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=stephen
      - MONGO_INITDB_ROOT_PASSWORD=steve1234