version: "3" # specify docker-compose version
services:
  nginx:
    image: nginx:stable-alpine # specify image to build container from
    ports:
      - "3000:80" # specify port mapping
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # mount nginx config
  node-app:
    build: . # use the Dockerfile in the current directory
    environment:
      - PORT=3000 # container
    depends_on: # container dependencies
      - mongo 
      - redis 
    links: # link to other containers
      - mongo
      - redis
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=stephen
      - MONGO_INITDB_ROOT_PASSWORD=steve1234
    volumes:
      - mongo-db:/data/db # persist data
  redis:
    image: redis

volumes: 
  mongo-db: 